### ISSUE TITLE
Wrong version number in package.mo

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [lochel/PNlib#65]
Hi!

I assume there is still the old version number in v2.1 package.mo

>within ;
>package PNlib
>  annotation(uses(Modelica(version="3.2.2")), version="2.0", conversion(noneFromVersion = "1.0", noneFromVersion = "1.1", noneFromVersion = "1.2", noneFromVersion = "1.3"));
>end PNlib;

This leads to problems in models as the 2.1 structure changed a lot.

Would be great to change these simply in the master branch.

Best

Georg

**Comment by tlask** [comment]
Is done, thanks for the info.
Have a nice Weekend.
