### ISSUE TITLE
Potential for a new incremental release 2.2

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [lochel/PNlib#67]
Dear @tlask, dear PNlib developers!

Thanks for taking my suggestions on library restructuring into account by #58, #66 etc.

I was wondering if there is the possibility to create a new release,maybe 2.2, of the library. This would be convinient to refer to and allows also the CI to check the latest update. Also the README.md should be updated as its states the version 2.0 to be the most recent release.

Thanks and BR

Georg

**Comment by casella** [comment]
I would also suggest to upgrade the `uses(Modelica)` annotation to 3.2.3, which was released 9 months ago. There is no good reason to keep using 3.2.3.

**Comment by lochel** [comment]
Thanks for the feedback. There is now a new release: version 2.2.
